
FROM golang:alpine3.19 AS builder

RUN apk add --no-cache \
	openssl \
	ca-certificates \
	make \
	bash \
	curl \
	gcc \
	musl-dev

ENV SUPERPOSITION_DIR /usr/local/src/superposition

WORKDIR ${SUPERPOSITION_DIR}

COPY go.mod .
COPY go.sum .

RUN go mod download

COPY lib lib/
COPY cmd cmd/

ENV INSTALL_DIR /bin

RUN sh -c 'cd cmd/graphql.ethereum && make install'

FROM scratch
WORKDIR /bin
COPY --from=builder /bin/graphql.ethereum .
CMD ["graphql.ethereum"]
